### ISSUE TITLE
Transition  2 audio clip

### ISSUE THREAD

**Issue by Avatarchik** [MathewHDYT/Unity-Audio-Manager#5]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MathewHDYT** [comment]
Could you describe your feature request in more detail? It is currently unclear what exactly is requested.

Perhaps the example scene can provide some help. [AdvancedExamples.cs](https://github.com/MathewHDYT/Unity-Audio-Manager/blob/main/Example_Project/Assets/Scripts/AdvancedExamples.cs)

**Comment by Avatarchik** [comment]
TransitionTo 
 Fade in and fade out transitions

**Comment by Avatarchik** [comment]
for example Play("Main_Menu");
then I call Play("Lobby");
and MainMenu smoothly reduces the volume
and the Lobby will gradually increase the volume from 0

**Comment by MathewHDYT** [comment]
This is how you would add a fade in effect on the volume, as can be seen in the [AdvancedExamples.cs](https://github.com/MathewHDYT/Unity-Audio-Manager/blob/main/Example_Project/Assets/Scripts/AdvancedExamples.cs) to any song.

```c#
am.SubscribeProgressCoroutine(fadeInSong.soundName, 0f, SongProgressCallback);
am.Play(fadeInSong.soundName);

public ProgressResponse InitFadeInSong(string name, float progress, ChildType child) {
    am.TryGetSource(name, out var source);
    source.Volume = 0f;
    am.LerpVolume(name, fadeInEndVolume, clipFadeInTime);
    return ProgressResponse.RESUB_IN_LOOP;
}
```

And this is how you would a fade out effect on the volume to any song.

```c#
am.TryGetSource(fadeOutSong.soundName, out var source);
float progress = ((source.Source.clip.length - clipFadeOutTime) / source.Source.clip.length);
am.SubscribeProgressCoroutine(fadeOutSong.soundName, progress, HandleFadeOutSong);
am.Play(fadeOutSong.soundName);

private ProgressResponse HandleFadeOutSong(string name, float progress, ChildType child) {
    am.LerpVolume(name, 0f, progress);
    return ProgressResponse.UNSUB;
}
```

-------------

For your case the `fadeInSong.soundName`, would be "Lobby" and `fadeOutSong.soundName` would be "Main_Menu".

**Comment by Avatarchik** [comment]
Can you provide a more detailed example, something I can’t figure out how to do?
I want to write a function
Transition (string fadeInSong, string fadeOutSong)

**Comment by MathewHDYT** [comment]
When exactly would you call this method in your code? Simply once at the startup.

Or do you call it by yourself, once you want to transition from the main_menu to the lobby song?

------------

For now this would be an Example method to fade out an already playing "Main_Menu" theme in 1 second and in that one second also starting fading in the "Lobby" theme.

```c#
private void TransitionWithFading(string fadeInSong, string fadeOutSong, float clipFadeInTime = 1f) {
    // Slowly decrease volume of the already playing song and slowly start to decrease the volume
    am.LerpVolume(fadeOutSong, 0f, clipFadeInTime);
    // Set volume to 0 before playing the song and slowly start to increase the volume
    am.TryGetSource(fadeInSong, out var source);
    float originalVolume = source.Volume;
    source.Volume = 0f;
    am.Play(fadeInSong);
    am.LerpVolume(fadeInSong, originalVolume, clipFadeInTime);
}
```
